### ISSUE TITLE
Have you thought about FlatBuffers?

### ISSUE THREAD

**Issue by bitmage** [holochain/holochain-serialization#24]
[Flatbuffers.rs](https://docs.rs/flatbuffers/0.6.1/flatbuffers/)

I think this is an interesting possibility for cross-language IPC due to the low overhead (no serialize/deserialize cost, it's just getters with offsets to a byte buffer), and ease of consumption in statically typed languages.  E.g. if I'm using Holochain in the data layer of my app, but my app is written in JS, Dart, Objective C, or Java.

Can you expand upon some of the needs and qualities that Holochain is looking for in its serialization layer?

**Comment by thedavidmeister** [comment]
https://github.com/holochain/holochain-serialization/tree/develop/crates/holochain_serialized_bytes#why

```
Holochain has specific requirements for serialization that need to be enforced
consistently in a "fool proof" way.

- Support arbitrary binary data
- Consistent bytes for _canonical representations_ of things for cryptographic use
- Support multiple languages
- Wide industry usage and tooling across many languages including Rust
- Reasonably fast and compact
- Human readable for debugging
- Able to preserve semantics for debugging
- Able to derive a sane serialization for the 99% of use cases
- Able to manually implement serialization for edge-cases (e.g. Merkle Trees)
- Able to form a base infrastructure layer for both wasm and networking
- Able to leverage the Rust compiler as much as possible to avoid bugs and help refactors

There are some additional goals of this crate that I'd like to make explicit
that informed some of the code design choices.

- Canonical representations of bytes of data should be enforced as canonical by the compiler at the type level
- For two systems sharing bytes and a shared type crate on the same version, round tripping bytes should be guaranteed safe by the compiler
- The design of `SerializedBytes` should be such that end-user-happ-devs should not need to be aware of it for BAU tasks
- Internal dependencies (e.g. serde messagepack handling) of this crate should not bleed into downstream concerns due to macros or whatever
- Everything internal to serialization should be upgradeable and refactorable without any external interface changes for consumers
```

i haven't used flatbuffers before, so i'll need help assessing it

the crate you linked:

- experimental support for rust only
- APIs may change between versions
- are the serialized bytes somewhat human readable/debuggable?
- doesn't seem to have many implementations for other languages outside those maintained by the flatbuffer authors, and a feature chart is needed to know which languages are well supported
![image](https://user-images.githubusercontent.com/629710/108457961-041e9380-728d-11eb-9840-b63fd99d15e6.png)
- isn't based on serde, so i'm not sure what expectations we should have about the stability of the serialized representation of things across different versions of itself, the rust compiler, and across languages

based on my (admittedly limited) benchmarking so far, the slowest part of our wasm calls seems to be setting up memory for the guest, i haven't seen serialization speed as a bottleneck (yet)

i have seen debugging of deserialization between wasm, the conductor, and javascript in the browser be a major friction point for developers, so ideally we don't want to make that any worse
